package com.crm.common;

import lombok.Getter;

/** 统一错误码（与契约 README 错误格式对齐）。 */
@Getter
public enum ErrorCode {
  BAD_REQUEST(400, "BAD_REQUEST", "请求参数错误"),
  INVALID_CREDENTIALS(401, "INVALID_CREDENTIALS", "用户名或密码错误"),
  UNAUTHORIZED(401, "UNAUTHORIZED", "未认证或令牌无效"),
  REFRESH_TOKEN_INVALID(401, "REFRESH_TOKEN_INVALID", "刷新令牌无效或已过期"),
  FORBIDDEN(403, "FORBIDDEN", "无权限执行该操作"),
  CUSTOMER_NOT_FOUND(404, "CUSTOMER_NOT_FOUND", "客户不存在"),
  OPPORTUNITY_NOT_FOUND(404, "OPPORTUNITY_NOT_FOUND", "商机不存在"),
  SALES_OPPORTUNITY_NOT_FOUND(404, "SALES_OPPORTUNITY_NOT_FOUND", "销售机会不存在"),
  FOLLOW_UP_NOT_FOUND(404, "FOLLOW_UP_NOT_FOUND", "跟进记录不存在"),
  LEAD_NOT_FOUND(404, "LEAD_NOT_FOUND", "线索不存在"),
  CONTACT_NOT_FOUND(404, "CONTACT_NOT_FOUND", "联系人不存在"),
  USER_NOT_FOUND(404, "USER_NOT_FOUND", "用户不存在"),
  USER_DUPLICATE(409, "USER_DUPLICATE", "用户名已存在"),
  CUSTOMER_DUPLICATE(409, "CUSTOMER_DUPLICATE", "相同名称与公司的客户已存在"),
  CONTACT_DUPLICATE(409, "CONTACT_DUPLICATE", "同一客户下相同姓名与电话的联系人已存在"),
  VERSION_CONFLICT(409, "VERSION_CONFLICT", "数据已被他人修改，请刷新后重试"),
  AMOUNT_RANGE_INVALID(422, "AMOUNT_RANGE_INVALID", "金额范围不合法"),
  AMOUNT_INVALID(422, "AMOUNT_INVALID", "金额不合法"),
  STAGE_INVALID(422, "STAGE_INVALID", "阶段不合法"),
  ALREADY_CLOSED(422, "ALREADY_CLOSED", "该销售机会已关闭"),
  CLOSE_RESULT_REQUIRED(422, "CLOSE_RESULT_REQUIRED", "关闭时必须提供赢单/输单结果"),
  OPPORTUNITY_CUSTOMER_MISMATCH(422, "OPPORTUNITY_CUSTOMER_MISMATCH", "商机与客户不匹配"),
  LEAD_ALREADY_CONVERTED(422, "LEAD_ALREADY_CONVERTED", "线索已转化，不可重复操作"),
  LEAD_INVALID_STATE(422, "LEAD_INVALID_STATE", "线索状态不允许该操作"),
  PRODUCT_NOT_FOUND(404, "PRODUCT_NOT_FOUND", "产品不存在"),
  PRODUCT_DUPLICATE(409, "PRODUCT_DUPLICATE", "产品编码已存在"),
  QUOTE_NOT_FOUND(404, "QUOTE_NOT_FOUND", "报价单不存在"),
  QUOTE_INVALID_STATE(409, "QUOTE_INVALID_STATE", "报价单当前状态不允许该操作"),
  CONTRACT_NOT_FOUND(404, "CONTRACT_NOT_FOUND", "合同不存在"),
  CONTRACT_INVALID_STATE(409, "CONTRACT_INVALID_STATE", "合同当前状态不允许该操作"),
  QUOTE_NOT_APPROVED(400, "QUOTE_NOT_APPROVED", "关联报价单未通过审批"),
  ATTACHMENT_NOT_FOUND(404, "ATTACHMENT_NOT_FOUND", "附件不存在"),
  ATTACHMENT_INVALID(400, "ATTACHMENT_INVALID", "附件类型或大小不合法"),
  TEMPLATE_NOT_FOUND(404, "TEMPLATE_NOT_FOUND", "合同模板不存在"),
  ORDER_NOT_FOUND(404, "ORDER_NOT_FOUND", "订单不存在"),
  CONTRACT_NOT_EFFECTIVE(400, "CONTRACT_NOT_EFFECTIVE", "关联合同未生效"),
  PLAN_NOT_FOUND(404, "PLAN_NOT_FOUND", "回款计划期次不存在"),
  PLAN_AMOUNT_MISMATCH(400, "PLAN_AMOUNT_MISMATCH", "期次金额合计与订单金额不一致"),
  PAYMENT_EXISTS(400, "PAYMENT_EXISTS", "存在已回款期次，不可删除"),
  PAYMENT_EXCEEDS(400, "PAYMENT_EXCEEDS", "回款金额超过该期应收"),
  ORDER_HAS_PAYMENTS(409, "ORDER_HAS_PAYMENTS", "存在回款记录，不可删除"),
  INTERNAL_ERROR(500, "INTERNAL_ERROR", "服务器内部错误");

  private final int status;
  private final String code;
  private final String message;

  ErrorCode(int status, String code, String message) {
    this.status = status;
    this.code = code;
    this.message = message;
  }
}
