-- H2 (MySQL 兼容模式) 测试 schema，与 V1__init.sql 保持字段一致
DROP TABLE IF EXISTS email_unsubscribe;
DROP TABLE IF EXISTS ticket_survey;
DROP TABLE IF EXISTS signature_record;
DROP TABLE IF EXISTS sales_opportunity_action;
DROP TABLE IF EXISTS stage_action_template;
DROP TABLE IF EXISTS report_template;
DROP TABLE IF EXISTS lead_score_config;
DROP TABLE IF EXISTS health_score_config;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS export_job;
DROP TABLE IF EXISTS custom_field_value;
DROP TABLE IF EXISTS custom_field;
DROP TABLE IF EXISTS sla_policy;
DROP TABLE IF EXISTS knowledge_article;
DROP TABLE IF EXISTS ticket_reply;
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS marketing_campaign;
DROP TABLE IF EXISTS workflow_notification;
DROP TABLE IF EXISTS workflow_execution_log;
DROP TABLE IF EXISTS workflow_rule;
DROP TABLE IF EXISTS customer_share;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS task_item;
DROP TABLE IF EXISTS payment_record;
DROP TABLE IF EXISTS payment_plan;
DROP TABLE IF EXISTS sales_order;
DROP TABLE IF EXISTS contract_attachment;
DROP TABLE IF EXISTS contract_template;
DROP TABLE IF EXISTS contract;
DROP TABLE IF EXISTS quote_item;
DROP TABLE IF EXISTS quote;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS sales_target;
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS follow_up;
DROP TABLE IF EXISTS sales_opportunity;
DROP TABLE IF EXISTS opportunity;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS `user`;

CREATE TABLE contact (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT       NOT NULL,
  name        VARCHAR(50)  NOT NULL,
  title       VARCHAR(50),
  phone       VARCHAR(30),
  email       VARCHAR(100),
  role        VARCHAR(30)  NOT NULL DEFAULT 'OTHER',
  remark      VARCHAR(500),
  deleted     INT          DEFAULT 0,
  version     INT          DEFAULT 0,
  created_by  BIGINT,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_contact_deleted_customer ON contact (deleted, customer_id);
CREATE INDEX idx_contact_deleted_name ON contact (deleted, name);
CREATE INDEX idx_contact_deleted_phone ON contact (deleted, phone);

CREATE TABLE audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    BIGINT,
  actor_name  VARCHAR(50),
  action      VARCHAR(50)  NOT NULL,
  entity_type VARCHAR(50)  NOT NULL,
  entity_id   BIGINT,
  detail      VARCHAR(500),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_log (created_at);

CREATE TABLE `user` (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  display_name  VARCHAR(50)  NOT NULL,
  role          VARCHAR(20)  NOT NULL,
  department_id BIGINT,
  data_scope    VARCHAR(20)  NOT NULL DEFAULT 'SELF',
  enabled       BOOLEAN      DEFAULT TRUE,
  last_login_at TIMESTAMP,
  token_version INT          DEFAULT 0,
  deleted       INT          DEFAULT 0,
  version       INT          DEFAULT 0,
  created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_username UNIQUE (username)
);
CREATE INDEX idx_user_department ON `user` (department_id);

CREATE TABLE customer (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(100) NOT NULL,
  company        VARCHAR(100) NOT NULL,
  contact_person VARCHAR(50),
  phone          VARCHAR(30),
  email          VARCHAR(100),
  address        VARCHAR(255),
  remark         VARCHAR(500),
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  deleted        INT          DEFAULT 0,
  version        INT          DEFAULT 0,
  created_by     BIGINT,
  owner_id       BIGINT,
  campaign_id    BIGINT,
  created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  active_key     VARCHAR(255) AS (CASE WHEN deleted = 0 THEN CONCAT(name, '||', company) ELSE NULL END),
  CONSTRAINT uk_customer_active_name_company UNIQUE (active_key)
);
CREATE INDEX idx_customer_deleted_company ON customer (deleted, company);
CREATE INDEX idx_customer_deleted_name ON customer (deleted, name);
CREATE INDEX idx_customer_deleted_phone ON customer (deleted, phone);
CREATE INDEX idx_customer_deleted_owner ON customer (deleted, owner_id);
CREATE INDEX idx_customer_campaign ON customer (campaign_id);

CREATE TABLE opportunity (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id         BIGINT       NOT NULL,
  name                VARCHAR(100) NOT NULL,
  expected_amount_min BIGINT       DEFAULT 0,
  expected_amount_max BIGINT       DEFAULT 0,
  remark              VARCHAR(500),
  status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
  deleted             INT          DEFAULT 0,
  version             INT          DEFAULT 0,
  created_by          BIGINT,
  created_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_opportunity_deleted_customer ON opportunity (deleted, customer_id);
CREATE INDEX idx_opportunity_deleted_name ON opportunity (deleted, name);

CREATE TABLE sales_opportunity (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id      BIGINT      NOT NULL,
  amount              BIGINT      DEFAULT 0,
  stage               VARCHAR(30) NOT NULL,
  expected_close_date DATE,
  close_result        VARCHAR(20),
  closed_at           TIMESTAMP,
  deleted             INT         DEFAULT 0,
  version             INT         DEFAULT 0,
  created_by          BIGINT,
  created_at          TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_so_deleted_stage ON sales_opportunity (deleted, stage);
CREATE INDEX idx_so_deleted_opportunity ON sales_opportunity (deleted, opportunity_id);

CREATE TABLE follow_up (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id       BIGINT,
  opportunity_id    BIGINT,
  lead_id           BIGINT,
  method            VARCHAR(20)   NOT NULL,
  content           VARCHAR(2000) NOT NULL,
  next_follow_up_at TIMESTAMP,
  follow_up_by      BIGINT        NOT NULL,
  deleted           INT           DEFAULT 0,
  version           INT           DEFAULT 0,
  created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_followup_customer_created ON follow_up (customer_id, created_at);
CREATE INDEX idx_followup_opportunity ON follow_up (opportunity_id);
CREATE INDEX idx_followup_lead ON follow_up (lead_id);

CREATE TABLE lead (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  VARCHAR(50)  NOT NULL,
  company               VARCHAR(100) NOT NULL,
  title                 VARCHAR(50),
  phone                 VARCHAR(30),
  email                 VARCHAR(100),
  source                VARCHAR(20)  NOT NULL DEFAULT 'OTHER',
  status                VARCHAR(20)  NOT NULL DEFAULT 'NEW',
  score                 INT          NOT NULL DEFAULT 0,
  owner_id              BIGINT,
  converted_customer_id BIGINT,
  converted_at          TIMESTAMP,
  campaign_id           BIGINT,
  remark                VARCHAR(500),
  deleted               INT          DEFAULT 0,
  version               INT          DEFAULT 0,
  created_by            BIGINT,
  created_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_lead_deleted_status ON lead (deleted, status);
CREATE INDEX idx_lead_deleted_owner ON lead (deleted, owner_id);
CREATE INDEX idx_lead_deleted_company ON lead (deleted, company);
CREATE INDEX idx_lead_deleted_name ON lead (deleted, name);
CREATE INDEX idx_lead_deleted_source ON lead (deleted, source);
CREATE INDEX idx_lead_campaign ON lead (campaign_id);

CREATE TABLE marketing_campaign (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  channel    VARCHAR(20)  NOT NULL,
  budget     BIGINT       NOT NULL DEFAULT 0,
  cost       BIGINT       NOT NULL DEFAULT 0,
  start_date DATE,
  end_date   DATE,
  status     VARCHAR(20)  NOT NULL DEFAULT 'PLANNING',
  deleted    INT          DEFAULT 0,
  version    INT          DEFAULT 0,
  created_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_campaign_channel_status ON marketing_campaign (channel, status);
CREATE INDEX idx_campaign_deleted_name ON marketing_campaign (deleted, name);

CREATE TABLE sales_target (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_month  VARCHAR(7) NOT NULL,
  target_amount BIGINT     NOT NULL,
  user_id       BIGINT,
  deleted       INT        DEFAULT 0,
  version       INT        DEFAULT 0,
  created_by    BIGINT,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  active_key    VARCHAR(64) AS (CASE WHEN deleted = 0 THEN CONCAT(COALESCE(user_id, 0), '||', target_month) ELSE NULL END),
  CONSTRAINT uk_sales_target_active UNIQUE (active_key)
);
CREATE INDEX idx_sales_target_deleted_month ON sales_target (deleted, target_month);

CREATE TABLE health_score_config (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dimension_key   VARCHAR(50) NOT NULL,
  dimension_label VARCHAR(100) NOT NULL,
  weight          INT         NOT NULL,
  params_json     VARCHAR(500),
  enabled         INT         DEFAULT 1,
  sort_order      INT         DEFAULT 0,
  deleted         INT         DEFAULT 0,
  version         INT         DEFAULT 0,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_health_score_dimension UNIQUE (dimension_key)
);
CREATE INDEX idx_health_score_enabled ON health_score_config (enabled, sort_order);

INSERT INTO health_score_config (dimension_key, dimension_label, weight, params_json, enabled, sort_order)
VALUES
  ('FOLLOWUP', '跟进活跃度', 30, '{"activeDays":30,"zeroDays":90}', 1, 1),
  ('PAYMENT', '回款及时性', 25, '{}', 1, 2),
  ('TICKET', '工单服务', 20, '{}', 1, 3),
  ('DEPTH', '合作深度', 15, '{"tiers":[{"amount":1000000,"score":15},{"amount":100000,"score":10}]}', 1, 4),
  ('ACTIVITY', '近期互动', 10, '{"activeDays":14}', 1, 5);

CREATE TABLE lead_score_config (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_key    VARCHAR(50) NOT NULL,
  rule_label  VARCHAR(100) NOT NULL,
  params_json VARCHAR(500),
  enabled     INT DEFAULT 1,
  sort_order  INT DEFAULT 0,
  deleted     INT DEFAULT 0,
  version     INT DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_lead_score_rule UNIQUE (rule_key)
);
CREATE INDEX idx_lead_score_enabled ON lead_score_config (enabled, sort_order);

INSERT INTO lead_score_config (rule_key, rule_label, params_json, enabled, sort_order)
VALUES
  ('SOURCE', '来源渠道', '{"REFERRAL":30,"WEBSITE":25,"EXHIBITION":20,"AD":15,"COLD_CALL":10,"OTHER":10}', 1, 1),
  ('INFO', '信息完整度', '{"fields":["company","title","phone","email"],"each":7.5}', 1, 2),
  ('FOLLOWUP', '跟进活跃度', '{"activeDays":7,"maxScore":25}', 1, 3),
  ('FRESHNESS', '互动时效', '{"activeDays":7,"zeroDays":30,"maxScore":15}', 1, 4),
  ('THRESHOLD', '颜色阈值', '{"red":40,"yellow":70}', 1, 5);

CREATE TABLE report_template (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100) NOT NULL,
  dimension     VARCHAR(30)  NOT NULL,
  metric        VARCHAR(20)  NOT NULL,
  granularity   VARCHAR(10),
  start_date    DATE,
  end_date      DATE,
  stage_filter  VARCHAR(30),
  created_by    BIGINT,
  deleted       INT DEFAULT 0,
  version       INT DEFAULT 0,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_report_template_creator ON report_template (created_by);

CREATE TABLE product (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code           VARCHAR(50)  NOT NULL,
  name           VARCHAR(100) NOT NULL,
  spec           VARCHAR(255),
  unit           VARCHAR(20),
  standard_price BIGINT       NOT NULL DEFAULT 0,
  status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
  deleted        INT          DEFAULT 0,
  version        INT          DEFAULT 0,
  created_by     BIGINT,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  active_key     VARCHAR(64) AS (CASE WHEN deleted = 0 THEN CONCAT('p||', code) ELSE NULL END),
  CONSTRAINT uk_product_active_code UNIQUE (active_key)
);
CREATE INDEX idx_product_deleted_status ON product (deleted, status);
CREATE INDEX idx_product_deleted_name ON product (deleted, name);

CREATE TABLE quote (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_no       VARCHAR(30) NOT NULL,
  customer_id    BIGINT      NOT NULL,
  opportunity_id BIGINT,
  valid_until    DATE,
  status         VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  total_amount   BIGINT      NOT NULL DEFAULT 0,
  remark         VARCHAR(500),
  approver_id    BIGINT,
  approved_at    TIMESTAMP,
  reject_reason  VARCHAR(500),
  deleted        INT         DEFAULT 0,
  version        INT         DEFAULT 0,
  created_by     BIGINT,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  active_key     VARCHAR(64) AS (CASE WHEN deleted = 0 THEN CONCAT('q||', quote_no) ELSE NULL END),
  CONSTRAINT uk_quote_active_no UNIQUE (active_key)
);
CREATE INDEX idx_quote_deleted_customer ON quote (deleted, customer_id);
CREATE INDEX idx_quote_deleted_status ON quote (deleted, status);

CREATE TABLE quote_item (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id     BIGINT       NOT NULL,
  product_id   BIGINT,
  product_name VARCHAR(100) NOT NULL,
  unit_price   BIGINT       NOT NULL,
  quantity     INT          NOT NULL,
  discount     DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
  line_total   BIGINT       NOT NULL,
  deleted      INT          DEFAULT 0,
  version      INT          DEFAULT 0,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_quote_item_quote ON quote_item (quote_id);

CREATE TABLE contract (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_no       VARCHAR(30)  NOT NULL,
  title             VARCHAR(200) NOT NULL,
  customer_id       BIGINT       NOT NULL,
  quote_id          BIGINT,
  amount            BIGINT       NOT NULL DEFAULT 0,
  start_date        DATE,
  end_date          DATE,
  content           CLOB,
  status            VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',
  approver_id       BIGINT,
  approved_at       TIMESTAMP,
  reject_reason     VARCHAR(500),
  effective_at      TIMESTAMP,
  terminated_reason VARCHAR(500),
  remark            VARCHAR(500),
  renewed_from_id   BIGINT,
  deleted           INT          DEFAULT 0,
  version           INT          DEFAULT 0,
  created_by        BIGINT,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  active_key        VARCHAR(64) AS (CASE WHEN deleted = 0 THEN CONCAT('c||', contract_no) ELSE NULL END),
  CONSTRAINT uk_contract_active_no UNIQUE (active_key)
);
CREATE INDEX idx_contract_deleted_customer ON contract (deleted, customer_id);
CREATE INDEX idx_contract_deleted_status ON contract (deleted, status);
CREATE INDEX idx_contract_renewed_from ON contract (renewed_from_id);

CREATE TABLE contract_attachment (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id  BIGINT       NOT NULL,
  file_name    VARCHAR(255) NOT NULL,
  file_path    VARCHAR(500) NOT NULL,
  file_size    BIGINT       NOT NULL,
  content_type VARCHAR(100),
  uploaded_by  BIGINT,
  deleted      INT          DEFAULT 0,
  version      INT          DEFAULT 0,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_attachment_contract ON contract_attachment (contract_id);

CREATE TABLE contract_template (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  content    CLOB         NOT NULL,
  status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
  deleted    INT          DEFAULT 0,
  version    INT          DEFAULT 0,
  created_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_template_deleted_status ON contract_template (deleted, status);

CREATE TABLE sales_order (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no    VARCHAR(30)  NOT NULL,
  title       VARCHAR(200) NOT NULL,
  customer_id BIGINT       NOT NULL,
  contract_id BIGINT,
  amount      BIGINT       NOT NULL DEFAULT 0,
  status      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
  description VARCHAR(500),
  deleted     INT          DEFAULT 0,
  version     INT          DEFAULT 0,
  created_by  BIGINT,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  active_key  VARCHAR(64) AS (CASE WHEN deleted = 0 THEN CONCAT('o||', order_no) ELSE NULL END),
  CONSTRAINT uk_order_active_no UNIQUE (active_key)
);
CREATE INDEX idx_order_deleted_customer ON sales_order (deleted, customer_id);
CREATE INDEX idx_order_deleted_status ON sales_order (deleted, status);

CREATE TABLE payment_plan (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT       NOT NULL,
  seq_no      INT          NOT NULL,
  amount      BIGINT       NOT NULL,
  due_date    DATE         NOT NULL,
  description VARCHAR(200),
  status      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
  deleted     INT          DEFAULT 0,
  version     INT          DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_plan_order ON payment_plan (order_id);

CREATE TABLE payment_record (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id     BIGINT       NOT NULL,
  order_id    BIGINT       NOT NULL,
  amount      BIGINT       NOT NULL,
  paid_at     DATE         NOT NULL,
  method      VARCHAR(20)  NOT NULL DEFAULT 'TRANSFER',
  recorded_by BIGINT,
  deleted     INT          DEFAULT 0,
  version     INT          DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_record_plan ON payment_record (plan_id);
CREATE INDEX idx_record_order ON payment_record (order_id);

CREATE TABLE task_item (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(200) NOT NULL,
  due_at      TIMESTAMP,
  priority    VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
  status      VARCHAR(20)  NOT NULL DEFAULT 'TODO',
  linked_type VARCHAR(20),
  linked_id   BIGINT,
  remark      VARCHAR(500),
  owner_id    BIGINT       NOT NULL,
  deleted     INT          DEFAULT 0,
  version     INT          DEFAULT 0,
  created_by  BIGINT,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_task_owner_status ON task_item (owner_id, status);
CREATE INDEX idx_task_owner_due ON task_item (owner_id, due_at);

CREATE TABLE department (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(50) NOT NULL,
  parent_id  BIGINT,
  deleted    INT          DEFAULT 0,
  version    INT          DEFAULT 0,
  created_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_department_parent ON department (parent_id);

CREATE TABLE customer_share (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id       BIGINT NOT NULL,
  shared_to_user_id BIGINT NOT NULL,
  shared_by         BIGINT,
  deleted           INT    DEFAULT 0,
  version           INT    DEFAULT 0,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  active_key        VARCHAR(64) AS (CASE WHEN deleted = 0 THEN CONCAT(customer_id, '||', shared_to_user_id) ELSE NULL END),
  CONSTRAINT uk_share_customer_user UNIQUE (active_key)
);
CREATE INDEX idx_share_customer ON customer_share (customer_id);
CREATE INDEX idx_share_to_user ON customer_share (shared_to_user_id);

CREATE TABLE workflow_rule (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(100) NOT NULL,
  event_type     VARCHAR(40)  NOT NULL,
  condition_json CLOB,
  action_type    VARCHAR(30)  NOT NULL,
  action_json    CLOB         NOT NULL,
  enabled        INT          DEFAULT 1,
  deleted        INT          DEFAULT 0,
  version        INT          DEFAULT 0,
  created_by     BIGINT,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_rule_event_enabled ON workflow_rule (event_type, enabled);

CREATE TABLE workflow_execution_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id       BIGINT        NOT NULL,
  event_type    VARCHAR(40)   NOT NULL,
  entity_type   VARCHAR(30),
  entity_id     BIGINT,
  matched       INT           DEFAULT 1,
  action_result VARCHAR(500),
  success       INT           DEFAULT 1,
  error_message VARCHAR(1000),
  deleted       INT           DEFAULT 0,
  version       INT           DEFAULT 0,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_log_rule ON workflow_execution_log (rule_id);
CREATE INDEX idx_log_event ON workflow_execution_log (event_type);

CREATE TABLE workflow_notification (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  message    VARCHAR(500) NOT NULL,
  read       INT          DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notif_user ON workflow_notification (user_id, read);

CREATE TABLE ticket (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id          BIGINT        NOT NULL,
  contact_id           BIGINT,
  title                VARCHAR(200)  NOT NULL,
  description          CLOB,
  priority             VARCHAR(20)   NOT NULL,
  status               VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
  assignee_id          BIGINT,
  sla_respond_deadline TIMESTAMP,
  sla_resolve_deadline TIMESTAMP,
  sla_status           VARCHAR(20),
  remark               VARCHAR(500),
  deleted              INT           DEFAULT 0,
  version              INT           DEFAULT 0,
  created_by           BIGINT,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ticket_status ON ticket (status);
CREATE INDEX idx_ticket_assignee ON ticket (assignee_id);
CREATE INDEX idx_ticket_customer ON ticket (customer_id);

CREATE TABLE ticket_reply (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  BIGINT       NOT NULL,
  replier_id BIGINT       NOT NULL,
  content    CLOB         NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ticket_reply_ticket ON ticket_reply (ticket_id);

CREATE TABLE knowledge_article (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category   VARCHAR(40)   NOT NULL,
  title      VARCHAR(200)  NOT NULL,
  content    CLOB,
  keywords   VARCHAR(500),
  status     VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
  author_id  BIGINT,
  deleted    INT           DEFAULT 0,
  version    INT           DEFAULT 0,
  created_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_article_status ON knowledge_article (status);
CREATE INDEX idx_article_category ON knowledge_article (category);

CREATE TABLE sla_policy (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  priority      VARCHAR(20) NOT NULL,
  respond_hours INT,
  resolve_hours INT,
  enabled       INT         DEFAULT 1,
  deleted       INT         DEFAULT 0,
  version       INT         DEFAULT 0,
  created_by    BIGINT,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_sla_policy_priority ON sla_policy (priority, deleted);

CREATE TABLE custom_field (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type VARCHAR(30)   NOT NULL,
  name        VARCHAR(50)   NOT NULL,
  field_type  VARCHAR(20)   NOT NULL,
  required    INT           DEFAULT 0,
  options     VARCHAR(1000),
  enabled     INT           DEFAULT 1,
  sort_order  INT           DEFAULT 0,
  deleted     INT           DEFAULT 0,
  version     INT           DEFAULT 0,
  created_by  BIGINT,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_field_entity_name ON custom_field (entity_type, name, deleted);
CREATE INDEX idx_field_entity_enabled ON custom_field (entity_type, enabled);

CREATE TABLE custom_field_value (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id    BIGINT         NOT NULL,
  entity_type VARCHAR(30)    NOT NULL,
  entity_id   BIGINT         NOT NULL,
  field_value VARCHAR(1000),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_field_entity_value ON custom_field_value (field_id, entity_id);
CREATE INDEX idx_value_entity ON custom_field_value (entity_type, entity_id);

CREATE TABLE export_job (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  export_type   VARCHAR(30)  NOT NULL,
  filter        CLOB,
  status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
  file_path     VARCHAR(500),
  row_count     BIGINT,
  error_message VARCHAR(1000),
  deleted       INT          DEFAULT 0,
  version       INT          DEFAULT 0,
  created_by    BIGINT,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at  TIMESTAMP
);
CREATE INDEX idx_export_user ON export_job (created_by, created_at);

CREATE TABLE notification (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT       NOT NULL,
  type        VARCHAR(30)  NOT NULL,
  message     VARCHAR(500) NOT NULL,
  read        INT          DEFAULT 0,
  entity_type VARCHAR(30),
  entity_id   BIGINT,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notif_user_read ON notification (user_id, read);
CREATE INDEX idx_notif_user_created ON notification (user_id, created_at);

-- 028-role-permissions
CREATE TABLE role (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(50)  NOT NULL,
  name        VARCHAR(50)  NOT NULL,
  description VARCHAR(255),
  data_scope  VARCHAR(20)  NOT NULL DEFAULT 'SELF',
  enabled     INT          DEFAULT 1,
  built_in    INT          DEFAULT 0,
  deleted     INT          DEFAULT 0,
  version     INT          DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_role_code ON role (code);

CREATE TABLE role_menu (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id  BIGINT       NOT NULL,
  menu_key VARCHAR(50)  NOT NULL
);
CREATE INDEX idx_role_menu_role ON role_menu (role_id);

CREATE TABLE role_permission (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id         BIGINT       NOT NULL,
  permission_code VARCHAR(50)  NOT NULL
);
CREATE INDEX idx_role_perm_role ON role_permission (role_id);

INSERT INTO role (code, name, description, data_scope, enabled, built_in) VALUES
('ADMIN', '系统管理员', '全部菜单与操作权限', 'ALL', 1, 1),
('SALES', '销售', '业务菜单与操作', 'SELF', 1, 1),
('SUPPORT', '客服', '客服菜单与操作', 'DEPT', 1, 1);

-- 内建角色菜单（简化：ADMIN 全量 28 项）
INSERT INTO role_menu (role_id, menu_key)
SELECT r.id, m.menu_key FROM role r JOIN (
  SELECT 'stats' AS menu_key UNION SELECT 'leads' UNION SELECT 'customers' UNION SELECT 'contacts'
  UNION SELECT 'opportunities' UNION SELECT 'sales-opportunities' UNION SELECT 'quotes'
  UNION SELECT 'contracts' UNION SELECT 'orders' UNION SELECT 'tasks' UNION SELECT 'products'
  UNION SELECT 'marketing' UNION SELECT 'tickets' UNION SELECT 'knowledge' UNION SELECT 'exports'
  UNION SELECT 'at-risk' UNION SELECT 'leaderboard' UNION SELECT 'reports' UNION SELECT 'suggestions'
  UNION SELECT 'board' UNION SELECT 'users' UNION SELECT 'departments' UNION SELECT 'workflows'
  UNION SELECT 'sla-policies' UNION SELECT 'custom-fields' UNION SELECT 'contract-templates'
  UNION SELECT 'audit-logs' UNION SELECT 'recycle-bin'
) m ON r.code = 'ADMIN';

INSERT INTO role_menu (role_id, menu_key)
SELECT r.id, m.menu_key FROM role r JOIN (
  SELECT 'stats' AS menu_key UNION SELECT 'leads' UNION SELECT 'customers' UNION SELECT 'contacts'
  UNION SELECT 'opportunities' UNION SELECT 'quotes' UNION SELECT 'contracts' UNION SELECT 'orders'
  UNION SELECT 'tasks' UNION SELECT 'products' UNION SELECT 'exports' UNION SELECT 'reports'
) m ON r.code = 'SALES';

INSERT INTO role_menu (role_id, menu_key)
SELECT r.id, m.menu_key FROM role r JOIN (
  SELECT 'stats' AS menu_key UNION SELECT 'customers' UNION SELECT 'contacts' UNION SELECT 'tickets'
  UNION SELECT 'knowledge'
) m ON r.code = 'SUPPORT';

-- 内建角色权限（ADMIN 全量）
INSERT INTO role_permission (role_id, permission_code)
SELECT r.id, p.permission_code FROM role r JOIN (
  SELECT 'customer:create' AS permission_code UNION SELECT 'customer:update' UNION SELECT 'customer:delete'
  UNION SELECT 'customer:transfer' UNION SELECT 'customer:import' UNION SELECT 'lead:create'
  UNION SELECT 'lead:update' UNION SELECT 'lead:delete' UNION SELECT 'lead:convert' UNION SELECT 'lead:assign'
  UNION SELECT 'opportunity:create' UNION SELECT 'opportunity:update' UNION SELECT 'opportunity:delete'
  UNION SELECT 'order:create' UNION SELECT 'order:update' UNION SELECT 'order:delete' UNION SELECT 'order:payment'
  UNION SELECT 'contract:create' UNION SELECT 'contract:update' UNION SELECT 'contract:delete' UNION SELECT 'contract:approve'
  UNION SELECT 'quote:create' UNION SELECT 'quote:update' UNION SELECT 'quote:delete' UNION SELECT 'quote:approve'
  UNION SELECT 'ticket:create' UNION SELECT 'ticket:update' UNION SELECT 'ticket:delete' UNION SELECT 'ticket:assign'
  UNION SELECT 'ticket:reply' UNION SELECT 'user:manage' UNION SELECT 'role:manage' UNION SELECT 'workflow:manage'
  UNION SELECT 'report:manage' UNION SELECT 'system:manage'
) p ON r.code = 'ADMIN';

INSERT INTO role_permission (role_id, permission_code)
SELECT r.id, p.permission_code FROM role r JOIN (
  SELECT 'customer:create' AS permission_code UNION SELECT 'customer:update' UNION SELECT 'customer:transfer'
  UNION SELECT 'lead:create' UNION SELECT 'lead:update' UNION SELECT 'lead:convert' UNION SELECT 'lead:assign'
  UNION SELECT 'opportunity:create' UNION SELECT 'opportunity:update'
  UNION SELECT 'order:create' UNION SELECT 'order:update' UNION SELECT 'order:payment'
  UNION SELECT 'contract:create' UNION SELECT 'contract:update'
  UNION SELECT 'quote:create' UNION SELECT 'quote:update'
) p ON r.code = 'SALES';

INSERT INTO role_permission (role_id, permission_code)
SELECT r.id, p.permission_code FROM role r JOIN (
  SELECT 'customer:create' AS permission_code UNION SELECT 'customer:update'
  UNION SELECT 'ticket:create' UNION SELECT 'ticket:update' UNION SELECT 'ticket:assign' UNION SELECT 'ticket:reply'
) p ON r.code = 'SUPPORT';

-- 031-customer-tags
CREATE TABLE tag (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(50) NOT NULL,
  color       VARCHAR(20),
  entity_type VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
  created_by  BIGINT,
  deleted     INT DEFAULT 0,
  version     INT DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_tag_name_entity ON tag (name, entity_type);

CREATE TABLE customer_tag (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  tag_id      BIGINT NOT NULL
);
CREATE INDEX idx_ct_customer ON customer_tag (customer_id);
CREATE INDEX idx_ct_tag ON customer_tag (tag_id);

CREATE TABLE segment (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  conditions  CLOB NOT NULL,
  created_by  BIGINT,
  deleted     INT DEFAULT 0,
  version     INT DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_segment_name ON segment (name);

-- 030-email-marketing
CREATE TABLE email_template (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(50) NOT NULL,
  subject     VARCHAR(200) NOT NULL,
  content     CLOB NOT NULL,
  category    VARCHAR(30) DEFAULT 'NOTICE',
  created_by  BIGINT,
  deleted     INT DEFAULT 0,
  version     INT DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_email_template_name ON email_template (name);

CREATE TABLE email_campaign (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id  BIGINT NOT NULL,
  name         VARCHAR(100) NOT NULL,
  source_type  VARCHAR(20) NOT NULL,
  source_ref   VARCHAR(255),
  total_count  INT DEFAULT 0,
  sent_count   INT DEFAULT 0,
  failed_count INT DEFAULT 0,
  open_count   INT DEFAULT 0,
  click_count  INT DEFAULT 0,
  status       VARCHAR(20) DEFAULT 'PENDING',
  variant      VARCHAR(10) DEFAULT 'NONE',
  subject_b    VARCHAR(255),
  winner       VARCHAR(10),
  created_by   BIGINT,
  deleted      INT DEFAULT 0,
  version      INT DEFAULT 0,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email_send_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id   BIGINT NOT NULL,
  customer_id   BIGINT,
  email         VARCHAR(100) NOT NULL,
  subject       VARCHAR(200) NOT NULL,
  content       CLOB NOT NULL,
  status        VARCHAR(20) DEFAULT 'SENT',
  variant       VARCHAR(10),
  error_message VARCHAR(255),
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email_unsubscribe (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           VARCHAR(255) NOT NULL,
  campaign_id     BIGINT,
  unsubscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_unsubscribe_email ON email_unsubscribe (email);

CREATE TABLE email_track (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  send_log_id BIGINT NOT NULL,
  track_type  VARCHAR(10) NOT NULL,
  click_url   VARCHAR(500),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 033-approval-flow
CREATE TABLE approval_flow (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(50) NOT NULL,
  business_type  VARCHAR(20) NOT NULL,
  nodes          CLOB NOT NULL,
  condition_json CLOB,
  enabled        INT DEFAULT 1,
  deleted        INT DEFAULT 0,
  version        INT DEFAULT 0,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_instance (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flow_id         BIGINT NOT NULL,
  business_type   VARCHAR(20) NOT NULL,
  business_id     BIGINT NOT NULL,
  title           VARCHAR(200) NOT NULL,
  status          VARCHAR(20) DEFAULT 'PENDING',
  current_task_id BIGINT,
  initiator       BIGINT NOT NULL,
  deleted         INT DEFAULT 0,
  version         INT DEFAULT 0,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_task (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id    BIGINT NOT NULL,
  node_name      VARCHAR(50) NOT NULL,
  approver_type  VARCHAR(20) NOT NULL,
  approver_value VARCHAR(100),
  approver_id    BIGINT,
  status         VARCHAR(20) DEFAULT 'PENDING',
  comment        VARCHAR(500),
  seq            INT DEFAULT 0,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id BIGINT NOT NULL,
  task_id     BIGINT,
  action      VARCHAR(20) NOT NULL,
  operator    BIGINT NOT NULL,
  comment     VARCHAR(500),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 035-field-visit
CREATE TABLE field_visit (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id      BIGINT NOT NULL,
  theme            VARCHAR(100) NOT NULL,
  visit_time       TIMESTAMP NOT NULL,
  duration_minutes INT,
  status           VARCHAR(20) DEFAULT 'PLANNED',
  latitude         DECIMAL(10,7),
  longitude        DECIMAL(10,7),
  location_text    VARCHAR(255),
  check_in_time    TIMESTAMP,
  summary          VARCHAR(1000),
  late_flag        INT DEFAULT 0,
  created_by       BIGINT,
  deleted          INT DEFAULT 0,
  version          INT DEFAULT 0,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 036-online-forms
CREATE TABLE form (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(50) NOT NULL,
  fields           CLOB NOT NULL,
  success_message  VARCHAR(200),
  source           VARCHAR(30) DEFAULT 'WEBSITE',
  status           VARCHAR(20) DEFAULT 'ENABLED',
  submission_count INT DEFAULT 0,
  created_by       BIGINT,
  deleted          INT DEFAULT 0,
  version          INT DEFAULT 0,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE form_submission (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id    BIGINT NOT NULL,
  payload    CLOB NOT NULL,
  client_ip  VARCHAR(45),
  lead_id    BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 037-announcements
CREATE TABLE announcement (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      VARCHAR(100) NOT NULL,
  content    CLOB NOT NULL,
  pinned     INT DEFAULT 0,
  expires_at TIMESTAMP,
  created_by BIGINT,
  deleted    INT DEFAULT 0,
  version    INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE announcement_read (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announcement_id BIGINT NOT NULL,
  user_id         BIGINT NOT NULL,
  read_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_announce_read ON announcement_read (announcement_id, user_id);

CREATE TABLE comment (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type VARCHAR(20) NOT NULL,
  entity_id   BIGINT NOT NULL,
  content     VARCHAR(1000) NOT NULL,
  author_id   BIGINT NOT NULL,
  deleted     INT DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 038-invoice
CREATE TABLE invoice (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     BIGINT NOT NULL,
  invoice_no   VARCHAR(30) NOT NULL,
  title        VARCHAR(200) NOT NULL,
  tax_no       VARCHAR(50),
  amount       BIGINT NOT NULL,
  invoice_type VARCHAR(20) DEFAULT 'GENERAL',
  status       VARCHAR(20) DEFAULT 'DRAFT',
  void_reason  VARCHAR(255),
  issued_at    TIMESTAMP,
  voided_at    TIMESTAMP,
  created_by   BIGINT,
  deleted      INT DEFAULT 0,
  version      INT DEFAULT 0,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_invoice_no ON invoice (invoice_no);

CREATE TABLE stage_action_template (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage       VARCHAR(30)  NOT NULL,
  action_name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  sort_order  INT          DEFAULT 0,
  required    INT          DEFAULT 0,
  enabled     INT          DEFAULT 1,
  deleted     INT          DEFAULT 0,
  version     INT          DEFAULT 0,
  created_by  BIGINT,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_template_stage_enabled ON stage_action_template (stage, enabled);
CREATE INDEX idx_template_stage_sort ON stage_action_template (stage, sort_order);

CREATE TABLE sales_opportunity_action (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id BIGINT NOT NULL,
  template_id    BIGINT NOT NULL,
  completed_by   BIGINT NOT NULL,
  completed_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_opp_action ON sales_opportunity_action (opportunity_id, template_id);
CREATE INDEX idx_opp_action_template ON sales_opportunity_action (template_id);

CREATE TABLE signature_record (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_type   VARCHAR(20) NOT NULL,
  business_id     BIGINT      NOT NULL,
  signer_id       BIGINT      NOT NULL,
  signer_name     VARCHAR(50),
  signature_image CLOB        NOT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_signature_business ON signature_record (business_type, business_id);

CREATE TABLE ticket_survey (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  BIGINT      NOT NULL,
  rating     INT         NOT NULL,
  comment    VARCHAR(500),
  created_by BIGINT      NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_survey_ticket ON ticket_survey (ticket_id);
