-- H2 (MySQL 兼容模式) 测试 schema，与 V1__init.sql 保持字段一致
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS follow_up;
DROP TABLE IF EXISTS sales_opportunity;
DROP TABLE IF EXISTS opportunity;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS `user`;

CREATE TABLE contact (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT       NOT NULL,
  name        VARCHAR(50)  NOT NULL,
  title       VARCHAR(50),
  phone       VARCHAR(30),
  email       VARCHAR(100),
  role        VARCHAR(30)  NOT NULL DEFAULT 'OTHER',
  remark      VARCHAR(500),
  deleted     INT          DEFAULT 0,
  version     INT          DEFAULT 0,
  created_by  BIGINT,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_contact_deleted_customer ON contact (deleted, customer_id);
CREATE INDEX idx_contact_deleted_name ON contact (deleted, name);
CREATE INDEX idx_contact_deleted_phone ON contact (deleted, phone);

CREATE TABLE audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    BIGINT,
  actor_name  VARCHAR(50),
  action      VARCHAR(50)  NOT NULL,
  entity_type VARCHAR(50)  NOT NULL,
  entity_id   BIGINT,
  detail      VARCHAR(500),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_log (created_at);

CREATE TABLE `user` (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  display_name  VARCHAR(50)  NOT NULL,
  role          VARCHAR(20)  NOT NULL,
  enabled       BOOLEAN      DEFAULT TRUE,
  last_login_at TIMESTAMP,
  token_version INT          DEFAULT 0,
  deleted       INT          DEFAULT 0,
  version       INT          DEFAULT 0,
  created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_username UNIQUE (username)
);

CREATE TABLE customer (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(100) NOT NULL,
  company        VARCHAR(100) NOT NULL,
  contact_person VARCHAR(50),
  phone          VARCHAR(30),
  email          VARCHAR(100),
  address        VARCHAR(255),
  remark         VARCHAR(500),
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  deleted        INT          DEFAULT 0,
  version        INT          DEFAULT 0,
  created_by     BIGINT,
  created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  active_key     VARCHAR(255) AS (CASE WHEN deleted = 0 THEN CONCAT(name, '||', company) ELSE NULL END),
  CONSTRAINT uk_customer_active_name_company UNIQUE (active_key)
);
CREATE INDEX idx_customer_deleted_company ON customer (deleted, company);
CREATE INDEX idx_customer_deleted_name ON customer (deleted, name);
CREATE INDEX idx_customer_deleted_phone ON customer (deleted, phone);

CREATE TABLE opportunity (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id         BIGINT       NOT NULL,
  name                VARCHAR(100) NOT NULL,
  expected_amount_min BIGINT       DEFAULT 0,
  expected_amount_max BIGINT       DEFAULT 0,
  remark              VARCHAR(500),
  status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
  deleted             INT          DEFAULT 0,
  version             INT          DEFAULT 0,
  created_by          BIGINT,
  created_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_opportunity_deleted_customer ON opportunity (deleted, customer_id);
CREATE INDEX idx_opportunity_deleted_name ON opportunity (deleted, name);

CREATE TABLE sales_opportunity (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id      BIGINT      NOT NULL,
  amount              BIGINT      DEFAULT 0,
  stage               VARCHAR(30) NOT NULL,
  expected_close_date DATE,
  close_result        VARCHAR(20),
  closed_at           TIMESTAMP,
  deleted             INT         DEFAULT 0,
  version             INT         DEFAULT 0,
  created_by          BIGINT,
  created_at          TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_so_deleted_stage ON sales_opportunity (deleted, stage);
CREATE INDEX idx_so_deleted_opportunity ON sales_opportunity (deleted, opportunity_id);

CREATE TABLE follow_up (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id       BIGINT,
  opportunity_id    BIGINT,
  lead_id           BIGINT,
  method            VARCHAR(20)   NOT NULL,
  content           VARCHAR(2000) NOT NULL,
  next_follow_up_at TIMESTAMP,
  follow_up_by      BIGINT        NOT NULL,
  deleted           INT           DEFAULT 0,
  version           INT           DEFAULT 0,
  created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_followup_customer_created ON follow_up (customer_id, created_at);
CREATE INDEX idx_followup_opportunity ON follow_up (opportunity_id);
CREATE INDEX idx_followup_lead ON follow_up (lead_id);

CREATE TABLE lead (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  VARCHAR(50)  NOT NULL,
  company               VARCHAR(100) NOT NULL,
  title                 VARCHAR(50),
  phone                 VARCHAR(30),
  email                 VARCHAR(100),
  source                VARCHAR(20)  NOT NULL DEFAULT 'OTHER',
  status                VARCHAR(20)  NOT NULL DEFAULT 'NEW',
  score                 INT          NOT NULL DEFAULT 0,
  owner_id              BIGINT,
  converted_customer_id BIGINT,
  converted_at          TIMESTAMP,
  remark                VARCHAR(500),
  deleted               INT          DEFAULT 0,
  version               INT          DEFAULT 0,
  created_by            BIGINT,
  created_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_lead_deleted_status ON lead (deleted, status);
CREATE INDEX idx_lead_deleted_owner ON lead (deleted, owner_id);
CREATE INDEX idx_lead_deleted_company ON lead (deleted, company);
CREATE INDEX idx_lead_deleted_name ON lead (deleted, name);
CREATE INDEX idx_lead_deleted_source ON lead (deleted, source);
